export const API_URL = process.env.NEXT_PUBLIC_API_URL_PATH; 
export const API_URL_OFFERS = process.env.NEXT_PUBLIC_API_URL_PATH_OFFERS;
export const API_URL_OUTDOOR = process.env.NEXT_PUBLIC_API_URL_PATH_OUTDOOR
export const API_URL_RECOMMENDED = process.env.NEXT_PUBLIC_API_URL_PATH_RECOMMENDED 
export const API_URL_PROUDLISTS = process.env.NEXT_PUBLIC_API_URL_PATH_PROUDLISTS; 
export const API_URL_PRODUCTSCARDINALLDATA = process.env.NEXT_PUBLIC_API_URL_PATH_PRODUCTSCARDINALLDATA; 
export const API_URL_YOUMAYLIKE = process.env.NEXT_PUBLIC_API_URL_PATH_YOUMAYLIKE;
export const API_URL_RELATEDPRODUCTS = process.env.NEXT_PUBLIC_API_URL_PATH_RELATEDPRODUCTS; 
export const API_URL_SAVEDFORLATER = process.env.NEXT_PUBLIC_API_URL_PATH_SAVEDFORLATER;
export const API_URL_MYCARDS = process.env.NEXT_PUBLIC_API_URL_PATH_MYCARDS;


